### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mahmutyoung** [Yazdun/chirp#1]
Hi Yazdun. 
Is that some error. When I try yo previev that is what I get after spin:

![WhatsApp Image 2023-04-14 at 20 41 03](https://user-images.githubusercontent.com/54088505/232118298-8ddeb8e4-50ee-4c9f-befb-87ba99b3ce50.jpeg)

PS: I did not try to login

**Comment by yazdanctx** [comment]
Hello and thanks for the heads up!

There were an issue with the database and I've just fixed it. Now you can access the app.
